//
// Provider System gRPC Services
//
// Sync Credit Provider related messages.
// This proto contains everything related to synchronize credit provider services
// accepted payload, returned response and method.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: v1/provsys/syncp.proto

package syncp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the sync credit request and response standard message.
type SyncCredit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncCredit) Reset() {
	*x = SyncCredit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_provsys_syncp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCredit) ProtoMessage() {}

func (x *SyncCredit) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provsys_syncp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCredit.ProtoReflect.Descriptor instead.
func (*SyncCredit) Descriptor() ([]byte, []int) {
	return file_v1_provsys_syncp_proto_rawDescGZIP(), []int{0}
}

// * Accepted request payload.
type SyncCredit_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PId          string  `protobuf:"bytes,1,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`                            /// pId of member.
	Currency     *string `protobuf:"bytes,2,opt,name=currency,proto3,oneof" json:"currency,omitempty"`                       /// Currency of member.
	ProviderCode string  `protobuf:"bytes,9,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"` /// provider code, e.g pgs.
}

func (x *SyncCredit_Req) Reset() {
	*x = SyncCredit_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_provsys_syncp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncCredit_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCredit_Req) ProtoMessage() {}

func (x *SyncCredit_Req) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provsys_syncp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCredit_Req.ProtoReflect.Descriptor instead.
func (*SyncCredit_Req) Descriptor() ([]byte, []int) {
	return file_v1_provsys_syncp_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SyncCredit_Req) GetPId() string {
	if x != nil {
		return x.PId
	}
	return ""
}

func (x *SyncCredit_Req) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *SyncCredit_Req) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

// * Response message that wil be returned in response "data".
type SyncCredit_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PId        string  `protobuf:"bytes,2,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`                       /// pId of member.
	Currency   string  `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                        /// Currency of member.
	Credit     float64 `protobuf:"fixed64,4,opt,name=credit,proto3" json:"credit,omitempty"`                          /// Credit amount of member.
	LastUpdate int64   `protobuf:"varint,6,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"` /// Last update credit info.
	IsLocked   bool    `protobuf:"varint,7,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`       /// Lock wallet status of member.
	IsDisabled bool    `protobuf:"varint,8,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"` /// Disable wallet status of member.
}

func (x *SyncCredit_Data) Reset() {
	*x = SyncCredit_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_provsys_syncp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncCredit_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCredit_Data) ProtoMessage() {}

func (x *SyncCredit_Data) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provsys_syncp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCredit_Data.ProtoReflect.Descriptor instead.
func (*SyncCredit_Data) Descriptor() ([]byte, []int) {
	return file_v1_provsys_syncp_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SyncCredit_Data) GetPId() string {
	if x != nil {
		return x.PId
	}
	return ""
}

func (x *SyncCredit_Data) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SyncCredit_Data) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *SyncCredit_Data) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *SyncCredit_Data) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *SyncCredit_Data) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

// * Response message that will be returned by sync credit services.
type SyncCredit_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` /// Status of the response.
	Code    int32                   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`       /// Code of the response.
	Error   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      /// Error info.
	Data    *SyncCredit_Data        `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`        /// Data of the response.
}

func (x *SyncCredit_Res) Reset() {
	*x = SyncCredit_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_provsys_syncp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncCredit_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCredit_Res) ProtoMessage() {}

func (x *SyncCredit_Res) ProtoReflect() protoreflect.Message {
	mi := &file_v1_provsys_syncp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCredit_Res.ProtoReflect.Descriptor instead.
func (*SyncCredit_Res) Descriptor() ([]byte, []int) {
	return file_v1_provsys_syncp_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SyncCredit_Res) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncCredit_Res) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncCredit_Res) GetError() *wrapperspb.StringValue {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SyncCredit_Res) GetData() *SyncCredit_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_provsys_syncp_proto protoreflect.FileDescriptor

var file_v1_provsys_syncp_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x73, 0x79, 0x73, 0x2f, 0x73, 0x79, 0x6e,
	0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x73, 0x79, 0x73, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x03, 0x0a, 0x0a,
	0x53, 0x79, 0x6e, 0x63, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x1a, 0x6b, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x12, 0x11, 0x0a, 0x04, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x70, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x1a, 0xac, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x11, 0x0a, 0x04, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x1a, 0x9f, 0x01, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x73,
	0x79, 0x73, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x57, 0x0a, 0x05, 0x53, 0x79, 0x6e, 0x63,
	0x70, 0x12, 0x4e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x12, 0x21, 0x2e, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x73, 0x79, 0x73, 0x2e,
	0x53, 0x79, 0x6e, 0x63, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x21,
	0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x73,
	0x79, 0x73, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x2e, 0x52, 0x65,
	0x73, 0x42, 0x33, 0x5a, 0x17, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x76, 0x73, 0x79, 0x73, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x70, 0xca, 0x02, 0x17, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x50, 0x72, 0x6f, 0x76, 0x53, 0x79, 0x73,
	0x5c, 0x53, 0x79, 0x6e, 0x63, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_provsys_syncp_proto_rawDescOnce sync.Once
	file_v1_provsys_syncp_proto_rawDescData = file_v1_provsys_syncp_proto_rawDesc
)

func file_v1_provsys_syncp_proto_rawDescGZIP() []byte {
	file_v1_provsys_syncp_proto_rawDescOnce.Do(func() {
		file_v1_provsys_syncp_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_provsys_syncp_proto_rawDescData)
	})
	return file_v1_provsys_syncp_proto_rawDescData
}

var file_v1_provsys_syncp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_provsys_syncp_proto_goTypes = []any{
	(*SyncCredit)(nil),             // 0: wallet.v1.provsys.SyncCredit
	(*SyncCredit_Req)(nil),         // 1: wallet.v1.provsys.SyncCredit.Req
	(*SyncCredit_Data)(nil),        // 2: wallet.v1.provsys.SyncCredit.Data
	(*SyncCredit_Res)(nil),         // 3: wallet.v1.provsys.SyncCredit.Res
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
}
var file_v1_provsys_syncp_proto_depIdxs = []int32{
	4, // 0: wallet.v1.provsys.SyncCredit.Res.error:type_name -> google.protobuf.StringValue
	2, // 1: wallet.v1.provsys.SyncCredit.Res.data:type_name -> wallet.v1.provsys.SyncCredit.Data
	1, // 2: wallet.v1.provsys.Syncp.Credit:input_type -> wallet.v1.provsys.SyncCredit.Req
	3, // 3: wallet.v1.provsys.Syncp.Credit:output_type -> wallet.v1.provsys.SyncCredit.Res
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_provsys_syncp_proto_init() }
func file_v1_provsys_syncp_proto_init() {
	if File_v1_provsys_syncp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_provsys_syncp_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SyncCredit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_provsys_syncp_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SyncCredit_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_provsys_syncp_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SyncCredit_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_provsys_syncp_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SyncCredit_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_provsys_syncp_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_provsys_syncp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_provsys_syncp_proto_goTypes,
		DependencyIndexes: file_v1_provsys_syncp_proto_depIdxs,
		MessageInfos:      file_v1_provsys_syncp_proto_msgTypes,
	}.Build()
	File_v1_provsys_syncp_proto = out.File
	file_v1_provsys_syncp_proto_rawDesc = nil
	file_v1_provsys_syncp_proto_goTypes = nil
	file_v1_provsys_syncp_proto_depIdxs = nil
}
